### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by koalex** [lucasb-eyer/d3-boundingbox#1]
Please add the "package.json" file to your repository so that it's easier for people to add your repository to a dependency.
[https://docs.npmjs.com/files/package.json](https://docs.npmjs.com/files/package.json)

**Comment by lucasb-eyer** [comment]
Hi, I have just added one, which I made with [a generator](http://jspkg.com/generator) because I've never made one before. So please let me know if it works fine or not, or if you have any other suggestions. If you have enough free time, could you also create a PR adding a small section to the readme on how to use it as a package, as I have no idea? Thanks.
